### ISSUE TITLE
Net::SMTPAuthenticationError - 530-5.5.1 Authentication Required. Learn more at :

### ISSUE THREAD

**Issue by Nuttdguy** [RailsApps/learn-rails#67]
I'm currently @ page 221 of the book.
I've encountered the error mentioned in the title. Through research, I uncovered an answer, via stackoverflow, 

""" [http://stackoverflow.com/questions/23251943/why-are-my-authentication-emails-not-working-i-get-an-authenticationerror] """

that stated the problem was with the environmental variables (user_name, password, domain) and ruby not picking it up. 

When I replaced "Rails.application.secrets.* " with my actual username and password, the contact form info was successfully received in my inbox with no errors. 

  config.action_mailer.smtp_settings = {
    address: "smtp.gmail.com",
    port: 587,
    domain: Rails.application.secrets.domain_name,
    authentication: 'login',
    enable_starttls_auto: true,
    user_name: Rails.application.secrets.gmail_email_provider_username,
    password: Rails.application.secrets.gmail_email_provider_password
  }

I created all of my environmental variables in ~.bashrc AND applied them as instructed in "secrets.yml"

development:
  gmail_email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <% ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <% ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: e9060e371e4fa67b

Why are environmental variables not being picked up and what's the solution to fix it? I want to continue the tutorial but need to keep my username and password a secret. Please provide some corrective options so I can continue with the tutorial.

Thanks!

**Comment by DanielKehoe** [comment]
Your file is different from the book so you may want to doublecheck and triplecheck everything for typos.
```
development:
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: very_long_random_string
```
If it's a local configuration issue with your Unix environment you'll need to investigate that further.
